delete from acteurs;
delete from films;
delete from  genres;
delete from  participants;
insert into genres ( id, libelle) values (1, 'Action');
insert into genres ( id, libelle) values (2, 'Animation');
insert into genres ( id, libelle) values (3, 'Comédie');
insert into genres ( id, libelle) values (4, 'Horreur');
insert into genres ( id, libelle) values (5, 'Thriller');
INSERT INTO PARTICIPANTS (prenom, nom) VALUES ('Steven', 'Spielberg');
INSERT INTO PARTICIPANTS (prenom, nom) VALUES ('David', 'Cronenberg');
INSERT INTO PARTICIPANTS (prenom, nom) VALUES ('Dany', 'Boon');
INSERT INTO PARTICIPANTS (prenom, nom) VALUES ('Richard', 'Attenborough');
INSERT INTO PARTICIPANTS (prenom, nom) VALUES ('Jeff', 'Goldblum');
INSERT INTO PARTICIPANTS (prenom, nom) VALUES ('Geena', 'Davis');
INSERT INTO PARTICIPANTS (prenom, nom) VALUES ('Mark', 'Rylance');
INSERT INTO PARTICIPANTS (prenom, nom) VALUES ('Ruby', 'Barnhill');
INSERT INTO PARTICIPANTS (prenom, nom) VALUES ('Kad', 'Merad');
INSERT INTO PARTICIPANTS (prenom, nom) VALUES ('Billy', 'Barnhill');
INSERT INTO PARTICIPANTS (prenom, nom) VALUES ('Billy', 'Wilder');
INSERT INTO PARTICIPANTS (prenom, nom) VALUES ('Marylin', 'Monroe');
INSERT INTO PARTICIPANTS (prenom, nom) VALUES ('Jack', 'Lemmon');
INSERT INTO PARTICIPANTS (prenom, nom) VALUES ('Tony', 'Curtis');
INSERT INTO PARTICIPANTS (prenom, nom) VALUES ('Shirley', 'Mac Laine');
INSERT INTO PARTICIPANTS (prenom, nom) VALUES ('Pierre', 'Coffin');
INSERT INTO PARTICIPANTS (prenom, nom) VALUES ('Quentin', 'Dupieux');
